---
- name: Learn about the when keyword
  hosts: drums:stuart

  vars:
    run_local: False

  tasks:
  - name: Run this task when a condition is met
    debug:
      msg: The condition was met
    when: run_local # | bool

  - name: Run this task when on the pete host when run_local is False
    debug:
      msg: This only runs on pete when run_local is False
    when: ansible_user == "pete" and not run_local

