---
 - name: A playbook that throws an error in the block.
   hosts: planetexpress

   tasks:
    - block:
       - shell: "echo 'My single task ran' > example.txt"
       - shell: "/bin/false" # This always returns a false value
         when: ansible_user == "bender"
       - shell: "echo 'My third task ran' >> example.txt"
      rescue:
      - name: rescue
        shell: "echo 'My rescue code ran. Maybe it undoes whatever the block tried to do' >> example.txt"
      always:
      - name: always
        shell: "echo 'This always runs. Maybe it is a commit, or an entry in a log' >> example.txt"

