- name: Thursday Role Challenge
  hosts: planetexpress

  pre_tasks:
  - name: Create an ~/nginx dir
    file:
      path: nginx
      state: directory
    notify:
    - nginx dir made

  roles:
  - nginx_role

  tasks:
  - name: perform an ls (on home dir)
    command: ls
    register: home_ls
    tags:
    - ls

  - name: debug of ls home dir
    debug:
      var: home_ls.stdout_lines
    tags:
    - ls

  post_tasks:
  - name: Remove the ~/nginx dir
    file:
      path: nginx
      state: absent

  handlers:
  - name: nginx dir made
    debug:
      msg: The nginx dir was made!
